before_install:
 - gem update --system
 - gem install bundler

language: ruby

os:
  - linux

addons:
  apt:
    update: true
    packages:
    - imagemagick
  homebrew:
    update: true
    packages:
    - imagemagick

rvm:
  - "2.7.1"
  - "3.0.0"
