before_install:
 - gem update --system
 - gem install bundler

language: ruby

os:
  - linux
  - osx

addons:
  apt:
    update: true
    packages:
    - imagemagick
  homebrew:
    update: true
    packages:
    - imagemagick

rvm:
  - "2.5.8"
  - "2.6.3"
  - "2.7.1"
